### ISSUE TITLE
Failed on Connection Exception

### ISSUE THREAD

**Issue by davideberdin** [big-data-europe/docker-hadoop-spark-workbench#26]
I am facing an issue where I am not able to let my Job to connect to the HDFS. Basically what I am trying to do is to run a simple Hadoop Job against the docker container. I follow the README and I was able to visualise all the UIs as described on the address of my docker machine (http://192.168.99.100:port). Everything works as expected but when I try to run the following Java code 
```
Job job = Job.getInstance();
job.set("fs.defaultFS", "hdfs://192.168.99.100:8020");  // Also tried with port 9000
   
// settings of the job here

return (job.waitForCompletion(true) ? 0 : 1);  <--- This line throw the exception
```
I get the following exception:

```
Exception in thread "main" java.net.ConnectException: Call From Pitagora.local/192.168.99.1 to 192.168.99.100:8020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:801)
        ....
```
The previous code works if I am using my **local** instance of Hadoop, but I am not able with the one in Docker. I tried to change port, ip, etc. but none seems working. 
Any advice ?

Thanks in advance

**Comment by earthquakesan** [comment]
@davideberdin hi!

In case you are using this command:
```
docker-compose up -d
```
then you are running [docker-compose.yml](https://github.com/big-data-europe/docker-hadoop-spark-workbench/blob/master/docker-compose.yml). In this docker-compose, the ports 8020 (9000) are not exposed. To make Hadoop available to the outside you need to add two port bindings to the "namenode" service as follows:
```
...
  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
      - 9000:9000
      - 8020:8020
...
```

**Comment by davideberdin** [comment]
Awesome! It worked like a charm! Thanks for you help @earthquakesan :)
