### ISSUE TITLE
MapReduce jobs causes Namenode to stop

### ISSUE THREAD

**Issue by georgiosgeorgiadis** [big-data-europe/docker-hadoop-spark-workbench#27]
Hi, 
we are facing the problem that when we are running our MapReduce jobs, the Namenode crushes, therefore our jobs cannot be completed. We have kept the ```hadoop.env``` as is here from this repository and the only thing that we changed was to expose the port 9000 in the ```docker-compose.yml``` so we can run our jobs. 

We tested the same code in the AWS EMR in production as well as in our local Hadoop installation and the jobs are working fine. 

The error we are having is the following:
```
java.io.EOFException: End of File Exception between local host is: "Administrators-MacBook-Pro-3.local/192.168.1.49"; destination host is: "192.168.99.100":9000; : java.io.EOFException; For more details see:  http://wiki.apache.org/hadoop/EOFException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
 ...
```
Once we obtained this error, we tried to reload ```http://192.168.99.100:50070/dfshealth.html#tab-overview``` and there was no response, hence, the namenode was not working anymore.

Any suggestions ? I have the feeling that there is a misconfiguration somewhere but we are not sure what.

Thanks!

**Comment by earthquakesan** [comment]
Hi @georgiosgeorgiadis!

Can you provide me with the minimal test case which cause this error? E.g. simple map reduce job. And the way how you submit it to the cluster.

**Comment by georgiosgeorgiadis** [comment]
Hi @earthquakesan ,

thank you for your quick response.

This is how I setup the job and run it:
```java
 protected Job job = null;

    public AJob() {
        setupJob();
    }

    private void setupJob() {
           this.job = Job.getInstance(Configurator.getJobConfiguration());

            this.job.setMapperClass(MatchHourlyMapper.class);
            this.job.setReducerClass(MatchHourlyReducer.class);
            this.job.setNumReduceTasks(3);

            FileInputFormat.setInputDirRecursive(this.job, true);

            FileSystem hdfs = FileSystem.get(Configurator.getHadoopConfiguration());
            FileInputFormat.addInputPaths(this.job, "path to dir");
            
           String outputPath = generateOutputPath();
           FileOutputFormat.setOutputPath(this.job, new Path(outputPath));

            this.job.setJarByClass(ETLScheduler.class);

            this.job.setInputFormatClass(TextInputFormat.class);
            this.job.setOutputFormatClass(TextOutputFormat.class);

            this.job.setMapOutputKeyClass(Text.class);
            this.job.setMapOutputValueClass(Text.class);

            this.job.setOutputKeyClass(NullWritable.class);
            this.job.setOutputValueClass(Text.class); 
     }

  public int runJob() {
        try {
            return (this.job.waitForCompletion(true) ? 0 : 1);
        } catch (IOException | InterruptedException | ClassNotFoundException e) {
            e.printStackTrace();
        }
        return 1;
    }
```

The Configurator:
```java
public class Configurator {

    public static Configuration getJobConfiguration() {
        JobConf jobConfiguration = new JobConf();

        jobConfiguration.set("job.name", "JobImport Job");

        jobConfiguration.set("mapreduce.framework.name", ETLConfiguration.getHadoopFramework());
        jobConfiguration.set("fs.s3n.awsAccessKeyId", Configuration.getAWSkey());
        jobConfiguration.set("fs.s3n.awsSecretAccessKey", Configuration.getAWSSecret());
        jobConfiguration.set("fs.defaultFS", ETLConfiguration.getAWSInputBucket());
        jobConfiguration.set("fs.AbstractFileSystem.s3a.impl", "org.apache.hadoop.fs.s3a.S3A");

        return jobConfiguration;
    }

    public static Configuration getHadoopConfiguration() {
        Configuration configuration = new Configuration();

        configuration.set("fs.defaultFS", ETLConfiguration.getHadoopHost());
        configuration.set("dfs.support.append", "true");
        configuration.set("dfs.client.use.datanode.hostname", "true");
        configuration.set("dfs.client.block.write.replace-datanode-on-failure.policy", "ALWAYS");
        configuration.set("dfs.client.block.write.replace-datanode-on-failure.best-effort", "true");
        configuration.set("fs.hdfs.impl", org.apache.hadoop.hdfs.DistributedFileSystem.class.getName());
        configuration.set("fs.file.impl", org.apache.hadoop.fs.LocalFileSystem.class.getName());

        return configuration;
    }

    public static Configuration getS3Configuration() {
        Configuration configuration = new Configuration();

        configuration.set("fs.s3n.awsAccessKeyId", ETLConfiguration.getAWSkey());
        configuration.set("fs.s3n.awsSecretAccessKey", ETLConfiguration.getAWSSecret());
        configuration.set("fs.defaultFS", ETLConfiguration.getAWSInputBucket());
        configuration.set("fs.AbstractFileSystem.s3a.impl", "org.apache.hadoop.fs.s3a.S3A");

        return configuration;
    }
}
```
The MatchHourlyMapper:
```java
public class MatchHourlyMapper extends Mapper<LongWritable, Text, Text, Text> {
    @Override
    public void map(LongWritable key, Text value, Context context) {

        String id;
        String line = value.toString();
        String[] matches = line.split("\\n");

        try {
            for (String match : matches) {
                JSONObject obj = new JSONObject(match);
                id = obj.getString("id");

                context.write(new Text(id), new Text(match));
            }
        } catch (JSONException | IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }
}
```
The MatchHourlyReducer:
```java
  @Override
    public void reduce(Text key, Iterable<Text> values, Context context) {
        try {
            JSONObject obj = new JSONObject();
            JSONArray matches = new JSONArray();
            JSONObject match, jo;

            for (Text val : values) {
                match = new JSONObject(val.toString());
                jo = new JSONObject().put("match", match);
                matches.put(jo);
            }

            obj.put("matches", matches);
            obj.put("id", key.toString());

            context.write(NullWritable.get(), new Text(obj.toString()));
        } catch (JSONException | IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }
```

I run the job from a org.quarz.job which is briefly outlined below:
```java
public class ScheduledJob {

    private JobDetail job = null;
    private Trigger trigger = null;

    public ScheduledJob(String name, String group, String trigger, int intervalsInHours, Class jobClass) {
        setup(name,group, trigger, intervalsInHours, jobClass);
    }

    private void setup(String name, String group, String trigger, int intervalsInHours, Class jobClass){
        Date midnight = this.getStartingDate();

        this.trigger = newTrigger()
                .withIdentity(trigger, group)
                .startNow()
                .withSchedule(simpleSchedule()
                        .withIntervalInHours(intervalsInHours)
                        .repeatForever())
                .build();

        this.job = newJob(jobClass)
                .withIdentity(name, group)
                .build();
    }

    public Trigger getTrigger() {
        return trigger;
    }

    public JobDetail getJob() {
        return this.job;
    }

    private Date getStartingDate() {
        return Date.from(ZonedDateTime.now().with(LocalTime.MIN).toInstant());
    }
}
```

Thanks

**Comment by earthquakesan** [comment]
Hi @georgiosgeorgiadis!

I had time to look into your issue and found out that configuration was not completely correct. I've updated hadoop docker images, you can find them here:
https://github.com/big-data-europe/docker-hadoop/tree/1.2.0-hadoop2.8-java8

To run the MapReduce cluster: 
```
  git clone https://github.com/big-data-europe/docker-hadoop && cd docker-hadoop
  git checkout 1.2.0-hadoop2.8-java8
  docker network create hadoop
  docker-compose up
```

Notice: You might need to restart namenode as it does not see datanode if it runs before it. In case you have errors in the log do:
```
docker restart namenode
```

Then navigate to http://localhost:8088 and look that you have 1 active node:
![alt text](https://u4882345.dl.dropboxusercontent.com/u/4882345/github/Resource_manager_healthy.png "Healthy Resource Manager")

To execute simple wordcount:
```
make wordcount
```

Hope it helps.

**Comment by georgiosgeorgiadis** [comment]
Thank you for your time @earthquakesan .

I will try it out today
