### ISSUE TITLE
java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode

### ISSUE THREAD

**Issue by dh12306** [big-data-europe/docker-hadoop-spark-workbench#63]
when i cloned this project , i run ' start-hadoop-spark-workbench-with-Hive.sh' ,
then there are some CONTAINERs running, but when i  'docker exec -it  spark-master /bin/bash' ,
and cd spark/bin , then run spark-shell , some thing happened:
this is my cmd:

scala> val textFile = sc.textFile("/spark/bin/words.txt")
textFile: org.apache.spark.rdd.RDD[String] = /spark/bin/words.txt MapPartitionsRDD[3] at textFile at <console>:20

scala> text
text   textFile
scala> textFile.count()
java.lang.IllegalArgumentException: java.net.UnknownHostException: namenode
  at org.apache.hadoop.security.SecurityUtil.buildTokenService(SecurityUtil.java:378)
  at org.apache.hadoop.hdfs.NameNodeProxies.createNonHAProxy(NameNodeProxies.java:310)
  at org.apache.hadoop.hdfs.NameNodeProxies.createProxy(NameNodeProxies.java:176)
  at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:678)
  at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:619)
  at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:149)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2669)
  at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:172)
  at org.apache.hadoop.mapred.JobConf.getWorkingDirectory(JobConf.java:656)
  at org.apache.hadoop.mapred.FileInputFormat.setInputPaths(FileInputFormat.java:438)
  at org.apache.hadoop.mapred.FileInputFormat.setInputPaths(FileInputFormat.java:411)
  at org.apache.spark.SparkContext$$anonfun$hadoopFile$1$$anonfun$29.apply(SparkContext.scala:1013)
  at org.apache.spark.SparkContext$$anonfun$hadoopFile$1$$anonfun$29.apply(SparkContext.scala:1013)
  at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:179)
  at org.apache.spark.rdd.HadoopRDD$$anonfun$getJobConf$6.apply(HadoopRDD.scala:179)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.rdd.HadoopRDD.getJobConf(HadoopRDD.scala:179)
  at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:198)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
  at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1965)
  at org.apache.spark.rdd.RDD.count(RDD.scala:1158)
  ... 46 elided
Caused by: java.net.UnknownHostException: namenode
  ... 79 more

i  want to use spark-sql or hive to exec some sql and connect to hive use python  or use pyspark,  can i achieve my aim ?

**Comment by dh12306** [comment]
![image](https://user-images.githubusercontent.com/20471681/55457914-fcfd2680-561d-11e9-9d83-684b0fba52b2.png)

this is my docker ps results

**Comment by OneCricketeer** [comment]
I think you need to use the correct compose file

`docker-compose -f docker-compose-hive.yml -exec...`

In any case, I do not see any services named namenode in your output there, so that might explain the error
