### ISSUE TITLE
Error when accessing Hue UI

### ISSUE THREAD

**Issue by cgiraldo** [big-data-europe/docker-hadoop-spark-workbench#9]
I cannot access hue in http://docker-host-ip:8088/

First time I access I can create an account with username hue and a password, but after registering the user the web servers responds with this error:
 
 Traceback (most recent call last):
> File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/wsgi.py", line 206, in __call__
    response = self.get_response(request)
  File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 194, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 229, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/opt/hue/build/env/lib/python2.7/site-packages/django_extensions-1.5.0-py2.7.egg/django_extensions/management/technical_response.py", line 5, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/opt/hue/desktop/core/src/desktop/views.py", line 283, in index
    return redirect(reverse('about:index'))
  File "/opt/hue/build/env/lib/python2.7/site-packages/Django-1.6.10-py2.7.egg/django/core/urlresolvers.py", line 532, in reverse
    key)
NoReverseMatch: u'about' is not a registered namespace

**Comment by earthquakesan** [comment]
@cgiraldo hi!
I disabled 'about' page in the hue configuration as it was freezing the whole application.
You have to specify the /home path to access hue, i.e. open
http://docker-host-ip:8088/home

**Comment by cgiraldo** [comment]
That solves my problem. Thank you!

**Comment by cgiraldo** [comment]
That solves my problem. Thank you
